#!/bin/bash
dir=$1; shift
script=$1; shift
nodemon --delay 2 -x 'gulp $dir && node-debug --cli --debug-brk --no-preload --save-live-edit' \
	--watch "lib/$dir" \
	-e js,jison,jisonlex \
	"dist/$dir/$script.js" $@
